apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: sharding
  namespace: garden-ixywdlfvei-ccknp
spec:
  addons:
    kubernetesDashboard:
      enabled: false
  cloudProfileName: stackit
  controlPlane:
    highAvailability:
      failureTolerance:
        type: zone
  extensions:
  - type: shoot-yawol
  hibernation:
    schedules:
    - start: "0 6 * * *"
      location: Europe/Berlin
  kubernetes:
    enableStaticTokenKubeconfig: false
    kubeControllerManager:
      nodeCIDRMaskSize: 24
    kubeProxy:
      mode: IPTables
    version: "1.28"
  maintenance:
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
    timeWindow:
      begin: 030000+0200
      end: 040000+0200
  networking:
    nodes: 10.250.0.0/16
    pods: 100.64.0.0/13
    services: 100.82.0.0/16
    providerConfig:
      apiVersion: calico.networking.extensions.gardener.cloud/v1alpha1
      kind: NetworkConfig
      backend: bird
      ipv4:
        mode: Always
        pool: ipip
    type: calico
  provider:
    controlPlaneConfig:
      apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      loadBalancerProvider: yawol
    infrastructureConfig:
      apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      floatingPoolName: floating-net
      networks:
        workers: 10.250.0.0/16
    type: openstack
    workers:
    # runs system and monitoring components (default worker pool)
    - name: system
      cri:
        name: containerd
      machine:
        architecture: amd64
        image:
          name: coreos
        type: g1a.8d
      maxSurge: 1
      maxUnavailable: 0
      maximum: 2
      minimum: 1
      systemComponents:
        allow: true
      volume:
        size: 50Gi
        type: storage_premium_perf1
      zones:
      - eu01-3
    # runs sharding components and webhosting-operator
    - name: sharding
      cri:
        name: containerd
      machine:
        architecture: amd64
        image:
          name: coreos
        type: g1a.8d
      maxSurge: 1
      maxUnavailable: 0
      maximum: 3
      minimum: 2
      systemComponents:
        allow: false
      labels:
        dedicated-for: sharding
      taints:
      - key: dedicated-for
        value: sharding
        effect: NoSchedule
      volume:
        size: 50Gi
        type: storage_premium_perf1
      zones:
      - eu01-3
    # runs experiment (optional)
    - name: experiment
      cri:
        name: containerd
      machine:
        architecture: amd64
        image:
          name: coreos
        type: g1a.8d
      maxSurge: 1
      maxUnavailable: 0
      maximum: 1
      minimum: 0
      systemComponents:
        allow: false
      labels:
        dedicated-for: experiment
      taints:
      - key: dedicated-for
        value: experiment
        effect: NoSchedule
      volume:
        size: 50Gi
        type: storage_premium_perf1
      zones:
      - eu01-3
  purpose: production
  region: RegionOne
  secretBindingName: q5bzeseo8o
