apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: ENABLE_SHARDING
          value: "false"
        # When comparing singleton vs sharded setups, the singleton will fail to verify the SLOs because it has too few
        # website workers. Increase the worker count to allow comparing the setups.
        - name: WEBSITE_CONCURRENT_SYNCS
          value: "50"
