{
 "title": "Sharding",
 "tags": [ "webhosting-operator" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "app",
    "query": {
     "query": "label_values(kube_shard_info{job=\"webhosting-exporter\"}, app)"
    }
   },
   {
    "name": "project",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", namespace=~\"project-.+\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_shard_info{app=\"$app\"})"
    }
   ]
  },
  {
   "title": "Ready Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_shard_state{app=\"$app\",state=\"ready\"})"
    }
   ]
  },
  {
   "title": "Shards per State",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_shard_state{app=\"$app\"}) by (state)",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Shard Readiness",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_shard_state{app=\"$app\",state=\"ready\"}) / sum(kube_shard_info{app=\"$app\"}) * 100"
    }
   ]
  },
  { "title": "Object Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Websites Count per Shard",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(kube_website_info{namespace=~\"$project\"} * on(shard) group_left kube_shard_info{app=\"$app\"}) by (shard)",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Websites Percentage per Shard",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_website_info{namespace=~\"$project\"} or 0*kube_shard_info{app=\"$app\"}) by (shard) / ignoring(shard) group_left sum(kube_website_info{namespace=~\"$project\"})",
     "legendFormat": "{{shard}}"
    }
   ]
  }
 ]
}