apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: sharding
  namespace: garden-timebertt
spec:
  addons:
    kubernetesDashboard:
      enabled: false
    nginxIngress:
      enabled: false
  cloudProfileName: stackit
  extensions:
  - type: shoot-yawol
  kubernetes:
    enableStaticTokenKubeconfig: false
    kubeControllerManager:
      nodeCIDRMaskSize: 20
    kubeProxy:
      mode: IPTables
    version: "1.25"
    verticalPodAutoscaler:
      enabled: true
  maintenance:
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
    timeWindow:
      begin: 030000+0200
      end: 040000+0200
  networking:
    nodes: 10.250.0.0/16
    pods: 100.96.0.0/11
    services: 100.64.0.0/13
    type: calico
  provider:
    controlPlaneConfig:
      apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      loadBalancerProvider: yawol
      zone: eu01-2
    infrastructureConfig:
      apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      floatingPoolName: floating-net
      networks:
        workers: 10.250.0.0/16
    type: openstack
    workers:
    # runs system and monitoring components, and sample websites
    - name: system
      cri:
        name: containerd
      machine:
        image:
          name: coreos
        type: g1a.8d
      maxSurge: 1
      maxUnavailable: 0
      maximum: 2
      minimum: 1
      systemComponents:
        allow: true
      volume:
        size: 50Gi
        type: storage_premium_perf1
      zones:
      - eu01-2
    # runs webhosting-operator
    - name: operator
      cri:
        name: containerd
      machine:
        image:
          name: coreos
        type: g1a.4d
      maxSurge: 1
      maxUnavailable: 0
      maximum: 1
      minimum: 1
      systemComponents:
        allow: false
      labels:
        dedicated-for: webhosting-operator
      taints:
      - key: dedicated-for
        value: webhosting-operator
        effect: NoSchedule
      volume:
        size: 50Gi
        type: storage_premium_perf1
      zones:
      - eu01-2
    # runs experiment
    - name: experiment
      cri:
        name: containerd
      machine:
        image:
          name: coreos
        type: g1a.4d
      maxSurge: 1
      maxUnavailable: 0
      maximum: 1
      minimum: 0
      systemComponents:
        allow: false
      labels:
        dedicated-for: experiment
      taints:
      - key: dedicated-for
        value: experiment
        effect: NoSchedule
      volume:
        size: 50Gi
        type: storage_premium_perf1
      zones:
      - eu01-2
  purpose: development
  region: RegionOne
  secretBindingName: timebertt
