apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: controller-sharding

resources:
- namespace.yaml
- sharding.timebertt.dev_controllerrings.yaml
