apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: controller-sharding

resources:
- namespace.yaml
- sharding.timebertt.dev_controllerrings.yaml
