apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: webhosting-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: webhosting-

# Labels to add to all resources and selectors.
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: webhosting-operator

images:
- name: controller
  newName: ghcr.io/timebertt/kubernetes-controller-sharding/webhosting-operator
  newTag: latest

resources:
- namespace.yaml
- manager.yaml
- service.yaml
- ../crds
- ../rbac
- metrics_auth.yaml
