apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: external-dns
        args:
        - --source=ingress
        - --source=service
        - --domain-filter=timebertt.dev
        - --provider=google
        - --log-format=json
        - --google-project=$(GOOGLE_PROJECT)
        - --google-zone-visibility=public
        - --policy=sync
        - --registry=txt
        - --txt-owner-id=shoot--ixywdlfvei--sharding-6d6c9d25-cab4-42ef-8a5b-8692bf615a15-ske
        - --interval=1m
        # ensure the records are not owned by short-lived acme solvers managed by cert-manager or website ingresses
        - --label-filter=acme.cert-manager.io/http01-solver!=true,app!=website
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secrets/service-account/service-account.json
        - name: GOOGLE_PROJECT
          valueFrom:
            secretKeyRef:
              name: google-clouddns-timebertt-dev
              key: project
        volumeMounts:
        - name: clouddns-credentials
          mountPath: /etc/secrets/service-account
          readOnly: true
      volumes:
      - name: clouddns-credentials
        secret:
          secretName: google-clouddns-timebertt-dev
