apiVersion: sharding.timebertt.dev/v1alpha1
kind: ControllerRing
metadata:
  name: example
spec:
  resources:
  - group: ""
    resource: secrets
    controlledResources:
    - group: ""
      resource: configmaps
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
