---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharder
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sharding.timebertt.dev
  resources:
  - controllerrings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sharding.timebertt.dev
  resources:
  - controllerrings/status
  verbs:
  - patch
  - update
