{
 "title": "Experiments",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "run_id",
    "query": {
     "query": "label_values(up{job=\"experiment\"},run_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Controller Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Website Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(namespace_run:kube_website_info:sum{run_id=~\"$run_id\"}) by (run_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Website Churn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n    rate(controller_runtime_reconcile_total{\n        job=\"experiment\", run_id=~\"$run_id\",\n        controller=~\"website-(generator|deleter|mutator)\",\n        result!=\"error\",\n    }[$__rate_interval])\n) by (controller)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Controller SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Queue Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n    sum by (run_id, le) (rate(\n        workqueue_queue_duration_seconds_bucket{\n            job=\"webhosting-operator\", name=\"website\", run_id=~\"$run_id\"\n        }[1m]\n    ))\n)",
     "legendFormat": "{{run_id}}-1m"
    },
    {
     "expr": "histogram_quantile(0.99,\n    sum by (run_id, le) (rate(\n        workqueue_queue_duration_seconds_bucket{\n            job=\"webhosting-operator\", name=\"website\", run_id=~\"$run_id\"\n        }[15m]\n    ))\n)",
     "legendFormat": "{{run_id}}-15m"
    }
   ]
  },
  {
   "title": "Reconciliation Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n    sum by (run_id, le) (rate(\n        experiment_website_reconciliation_duration_seconds_bucket{\n            job=\"experiment\", run_id=~\"$run_id\"\n        }[1m]\n    ))\n)",
     "legendFormat": "{{run_id}}-1m"
    },
    {
     "expr": "histogram_quantile(0.99,\n    sum by (run_id, le) (rate(\n        experiment_website_reconciliation_duration_seconds_bucket{\n            job=\"experiment\", run_id=~\"$run_id\"\n        }[15m]\n    ))\n)",
     "legendFormat": "{{run_id}}-15m"
    }
   ]
  },
  { "title": "Controller Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (rate(\n    container_cpu_usage_seconds_total{\n        pod=~\"sharder-.+|webhosting-operator-.+\",\n        container=~\"sharder|manager\"\n    }[1m]\n)) * on (namespace, pod) group_left (run_id) max by (namespace, pod, run_id) (kube_pod_labels{run_id=~\"$run_id\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, run_id) (\n    go_memory_classes_total_bytes{pod=~\"sharder-.+|webhosting-operator-.+\",run_id=~\"$run_id\"}\n    - go_memory_classes_heap_released_bytes{\n        pod=~\"sharder-.+|webhosting-operator-.+\",\n        run_id=~\"$run_id\"\n    }\n    - go_memory_classes_heap_unused_bytes{\n        pod=~\"sharder-.+|webhosting-operator-.+\",\n        run_id=~\"$run_id\"\n    }\n    - go_memory_classes_heap_free_bytes{\n        pod=~\"sharder-.+|webhosting-operator-.+\",\n        run_id=~\"$run_id\"\n    }\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Receive by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, run_id) (rate(\n    container_network_receive_bytes_total{\n        pod=~\"sharder-.+|webhosting-operator-.+\"\n    }[1m]\n)) * on (namespace, pod) group_left (run_id) max by (namespace, pod, run_id) (kube_pod_labels{run_id=~\"$run_id\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Transmit by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, run_id) (rate(\n    container_network_transmit_bytes_total{\n        pod=~\"sharder-.+|webhosting-operator-.+\"\n    }[1m]\n)) * on (namespace, pod) group_left (run_id) max by (namespace, pod, run_id) (kube_pod_labels{run_id=~\"$run_id\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}