{
 "title": "Sharding",
 "tags": [ "webhosting-operator" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "clusterring",
    "query": {
     "query": "label_values(kube_shard_info,clusterring)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(controller_sharding_assignments_total, group)"
    }
   },
   {
    "name": "resource",
    "query": {
     "query": "label_values(controller_sharding_assignments_total{group=~\"$group\"}, resource)"
    }
   },
   {
    "name": "project",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", namespace=~\"project-.+\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available Shards",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_shard_state{clusterring=\"$clusterring\", state=~\"ready|expired|uncertain\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Shards",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_shard_info{clusterring=\"$clusterring\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Shards per State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_shard_state{clusterring=\"$clusterring\"}) by (state)",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Shard Readiness",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(kube_shard_state{clusterring=\"$clusterring\",state=\"ready\"}) or vector(0)) / (sum(kube_shard_info{clusterring=\"$clusterring\"}) or vector(0)) * 100"
    }
   ]
  },
  {
   "title": "Object Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_shard:kube_website_shard:sum{namespace=~\"$project\",shard!=\"\"} or 0*sum(kube_shard_info{clusterring=\"$clusterring\"}) by (shard)) by (shard) / ignoring(shard) group_left sum(namespace_shard:kube_website_shard:sum{namespace=~\"$project\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Object Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Websites Count per Shard",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(namespace_shard:kube_website_shard:sum{namespace=~\"$project\",shard!=\"\"} or 0*sum(kube_shard_info{clusterring=\"$clusterring\"}) by (shard)) by (shard)",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Websites Percentage per Shard",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(namespace_shard:kube_website_shard:sum{namespace=~\"$project\",shard!=\"\"} or 0*sum(kube_shard_info{clusterring=\"$clusterring\"}) by (shard)) by (shard) / ignoring(shard) group_left sum(namespace_shard:kube_website_shard:sum{namespace=~\"$project\"})",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Websites Count per Sharding State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(namespace_shard_drain:kube_website_shard:sum{namespace=~\"$project\",shard!=\"\",drain=\"\"} * on(shard) group_left kube_shard_state{clusterring=\"$clusterring\",state=\"ready\"}) or vector(0)",
     "legendFormat": "Assigned"
    },
    {
     "expr": "sum(namespace_shard_drain:kube_website_shard:sum{namespace=~\"$project\",shard!=\"\",drain=\"\"} * on(shard) group_left max(kube_shard_state{clusterring=\"$clusterring\",state!=\"ready\"}) by (shard)) or vector(0)",
     "legendFormat": "Assigned to unready"
    },
    {
     "expr": "sum(namespace_shard_drain:kube_website_shard:sum{namespace=~\"$project\",drain!=\"\"}) or vector(0)",
     "legendFormat": "Draining"
    },
    {
     "expr": "sum(namespace_shard_drain:kube_website_shard:sum{namespace=~\"$project\",shard=\"\"}) or vector(0)",
     "legendFormat": "Unassigned"
    }
   ]
  },
  { "title": "Sharder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Sharder Actions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(controller_sharding_assignments_total{group=~\"$group\", resource=~\"$resource\"}[$__rate_interval]))",
     "legendFormat": "Assignments"
    },
    {
     "expr": "sum(rate(controller_sharding_movements_total{group=~\"$group\", resource=~\"$resource\"}[$__rate_interval]))",
     "legendFormat": "Movements"
    },
    {
     "expr": "sum(rate(controller_sharding_drains_total{group=~\"$group\", resource=~\"$resource\"}[$__rate_interval]))",
     "legendFormat": "Drains"
    }
   ]
  },
  {
   "title": "Sharder Assignments by resource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(controller_sharding_assignments_total{group=~\"$group\", resource=~\"$resource\"}[$__rate_interval])) by (resource)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Sharder Webhook Requests by code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_webhook_requests_total{job=\"sharder\", webhook=\"/webhooks/sharder/\"}[$__rate_interval])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sharder Webhook Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(controller_runtime_webhook_latency_seconds_bucket{job=\"sharder\", webhook=\"/webhooks/sharder/\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_webhook_latency_seconds_bucket{job=\"sharder\", webhook=\"/webhooks/sharder/\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(controller_runtime_webhook_latency_seconds_bucket{job=\"sharder\", webhook=\"/webhooks/sharder/\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Sharder Ring Calculations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(controller_sharding_ring_calculations_total{name=\"$clusterring\"}[$__rate_interval]))",
     "legendFormat": "Ring Calculations"
    }
   ]
  }
 ]
}