apiVersion: apps/v1
kind: Deployment
metadata:
  name: checksum-controller
spec:
  replicas: 3
  template:
    spec:
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
      containers:
      - name: checksum-controller
        image: checksum-controller:latest
        args:
        - --controllerring=checksum-controller
        - --zap-log-level=debug
        env:
        - name: DISABLE_HTTP2
          value: "true"
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
      serviceAccountName: checksum-controller
      terminationGracePeriodSeconds: 10
