apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: controller-sharding
    app.kubernetes.io/component: checksum-controller

images:
- name: checksum-controller
  newName: ghcr.io/timebertt/kubernetes-controller-sharding/checksum-controller
  newTag: latest

resources:
- ../controllerring
- deployment.yaml
- rbac.yaml
- serviceaccount.yaml
