---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sharding:checksum-controller
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sharding:checksum-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sharding:checksum-controller
subjects:
- kind: ServiceAccount
  name: checksum-controller
