apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: ENABLE_SHARDING
          value: "true"
