apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../webhosting-operator

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - dashboards/sharding.json
  - dashboards/webhosting.json
  - dashboards/experiments.json
  name: grafana-dashboards-sharding
  namespace: monitoring
  options:
    labels:
      grafana_dashboard: "true"
