apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: kube-apiserver
  namespace: shoot--timebertt--sharding
spec:
  failurePolicy: Fail
  rules:
  # set static replicas on kube-apiserver to ensure similar evaluation environment between load test runs
  # if the cluster is hibernated (spec.replicas=0), this rule is skipped
  - name: replicas
    match:
      any:
      - resources:
          kinds:
          - Deployment
          selector:
            matchLabels:
              app: kubernetes
              role: apiserver
    preconditions:
      all:
      # Only patch spec.replicas if the control plane is not hibernated, i.e., if spec.replicas>=1.
      # NB: gardenlet deploys kube-apiserver with spec.replicas=null which is defaulted after the policy webhook call
      # to spec.replicas=1. Hence, treat spec.replicas=null the same way as spec.replicas=1.
      - key: "{{ request.object.spec.replicas || `1` }}"
        operator: GreaterThan
        value: 0
    mutate:
      patchStrategicMerge:
        spec:
          replicas: 4
  # set static requests/limits on kube-apiserver to ensure similar evaluation environment between load test runs
  - name: resources
    match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              app: kubernetes
              role: apiserver
    mutate:
      patchStrategicMerge:
        spec:
          containers:
          - name: kube-apiserver
            resources:
              requests:
                cpu: 12000m
                memory: 12Gi
              limits:
                cpu: 12000m
                memory: 12Gi
            # set GOMAXPROCS to CPU quota to minimize goroutine scheduling contention (CPU throttling)
            env:
            - name: GOMAXPROCS
              value: "12"
  # schedule kube-apiserver on high-cpu worker pool for stable performance
  - name: add-scheduling-constraints
    match:
      any:
      - resources:
          kinds:
          - Pod
          selector:
            matchLabels:
              app: kubernetes
              role: apiserver
    mutate:
      patchesJson6902: |-
        - op: add
          path: "/spec/tolerations/-"
          value: {"key":"high-cpu","operator":"Equal","value":"true","effect":"NoSchedule"}
        - op: add
          path: "/spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms"
          value: [{"matchExpressions": [{"key":"high-cpu","operator":"In","values":["true"]}]}]
