apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This kustomization contains policies for manipulating shoot control plane components.
# For this to work, kyverno needs to be installed on the seed cluster.

resources:
- etcd-main.yaml
- kube-apiserver.yaml
- kube-controller-manager.yaml
