apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: webhosting-system

commonLabels:
  app.kubernetes.io/name: webhosting-operator

resources:
# provide prometheus running in namespace "monitoring" with the permissions required for service discovery in namespace
# "webhosting-system"
- prometheus_rbac.yaml
- servicemonitor.yaml
- prometheusrule.yaml
