apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webhosting-operator
spec:
  endpoints:
  - path: /metrics
    port: https
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 10s
    scrapeTimeout: 10s
    tlsConfig:
      insecureSkipVerify: true
    relabelings:
    - action: labelmap
      regex: "__meta_kubernetes_pod_label_label_prometheus_io_(.*)"
      replacement: "${1}"
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: webhosting-operator
