apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ingress-nginx

resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.1/deploy/static/provider/cloud/deploy.yaml

patches:
- path: patch_default_ingress_class.yaml
- path: patch_controller_resources.yaml
# Delete validation webhook for Ingresses.
# We don't need or want validation for Ingress objects in the development and load testing setup. It results in high
# latency for API requests and CPU waste during load tests.
- patch: |
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: ingress-nginx-admission
    $patch: delete
# This job fails if the ValidatingWebhookConfiguration does not exist. Drop it as well.
# Note: we can't drop the ingress-nginx-admission-create job, which creates the webhook certificate. Without this,
# the ingress-nginx-controller won't start.
- patch: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: ingress-nginx-admission-patch
      namespace: ingress-nginx
    $patch: delete
