apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sharding-system

generatorOptions:
  disableNameSuffixHash: true

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: controller-sharding

images:
- name: sharder
  newName: ghcr.io/timebertt/kubernetes-controller-sharding/sharder
  newTag: latest

resources:
- deployment.yaml
- poddisruptionbudget.yaml
- service.yaml
- ../rbac

configMapGenerator:
- name: sharder-config
  options:
    labels:
      app.kubernetes.io/component: sharder
  files:
  - config=../sharder/config.yaml
