apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.18.1/cert-manager.yaml

patches:
# lower the webhook timeouts to make the webhooks compliant with gardener's requirements
- path: patch-validatingwebhook.yaml
- path: patch-mutatingwebhook.yaml
