{
 "title": "Controller Runtime / Client-Go",
 "tags": [ "controller-runtime" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{}, job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{job=\"$job\"}, pod)"
    }
   },
   {
    "name": "verb",
    "query": {
     "query": "label_values(rest_client_requests_total{job=\"$job\"}, method)"
    }
   },
   {
    "name": "code",
    "query": {
     "query": "label_values(rest_client_requests_total{job=\"$job\"}, code)"
    }
   },
   { "name": "percentile", "query": "90,95,99" }
  ]
 },
 "panels": [
  { "title": "Request Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate by pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",pod=~\"$pod\",method=~\"$verb\",code=~\"$code\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Rate by code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",pod=~\"$pod\",method=~\"$verb\",code=~\"$code\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Request Rate by verb",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",pod=~\"$pod\",method=~\"$verb\",code=~\"$code\"}[$__rate_interval])) by (method)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  { "title": "Request / Response Sizes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Request Size by pod (P$percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(rest_client_request_size_bytes_bucket{job=\"$job\",pod=~\"$pod\"}[$__rate_interval])) by (pod,le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Size by verb (P$percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(rest_client_request_size_bytes_bucket{job=\"$job\",pod=~\"$pod\",verb=~\"$verb\"}[$__rate_interval])) by (verb,le))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Response Size by pod (P$percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(rest_client_response_size_bytes_bucket{job=\"$job\",pod=~\"$pod\"}[$__rate_interval])) by (pod,le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Response Size by verb (P$percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(rest_client_response_size_bytes_bucket{job=\"$job\",pod=~\"$pod\",verb=~\"$verb\"}[$__rate_interval])) by (verb,le))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  { "title": "Rate Limiter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Rate Limiter Duration by pod (P$percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(rest_client_rate_limiter_duration_seconds_bucket{job=\"$job\",pod=~\"$pod\",verb=~\"$verb\"}[$__rate_interval])) by (pod,le))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate Limiter Duration by verb (P$percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(rate(rest_client_rate_limiter_duration_seconds_bucket{job=\"$job\",pod=~\"$pod\",verb=~\"$verb\"}[$__rate_interval])) by (verb,le))",
     "legendFormat": "{{verb}}"
    }
   ]
  }
 ]
}