apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sharding:exporter
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sharding.timebertt.dev
  resources:
  - controllerrings
  verbs:
  - get
  - list
  - watch
