kind: CustomResourceStateMetrics
spec:
  resources:
  # shard metrics
  - metricNamePrefix: kube_shard
    groupVersionKind:
      group: coordination.k8s.io
      version: v1
      kind: Lease
    labelsFromPath:
      namespace: [metadata, namespace]
      shard: [metadata, name]
      controllerring: [metadata, labels, alpha.sharding.timebertt.dev/controllerring]
    metrics:
    - name: info
      help: "Information about a Shard"
      each:
        type: Info
        info:
          labelsFromPath:
            uid: [metadata, uid]
    - name: state
      help: "The Shard's current state observed by the shardlease controller"
      each:
        type: StateSet
        stateSet:
          labelName: state
          path: [metadata, labels, alpha.sharding.timebertt.dev/state]
          list: [orphaned, dead, uncertain, expired, ready, unknown]
      # The usual leader election leases don't have the state label making the generator log errors.
      # Hence, decrease verbosity of such errors to reduce distraction.
      errorLogV: 4
  # controllerring metrics
  - metricNamePrefix: kube_controllerring
    groupVersionKind:
      group: sharding.timebertt.dev
      version: v1alpha1
      kind: ControllerRing
    labelsFromPath:
      controllerring: [metadata, name]
      uid: [metadata, uid]
    metrics:
    - name: metadata_generation
      help: "The generation of a ControllerRing"
      each:
        type: Gauge
        gauge:
          path: [metadata, generation]
    - name: observed_generation
      help: "The latest generation observed by the ControllerRing controller"
      each:
        type: Gauge
        gauge:
          path: [status, observedGeneration]
    - name: status_shards
      help: "The ControllerRing's total number of shards observed by the ControllerRing controller"
      each:
        type: Gauge
        gauge:
          path: [status, shards]
    - name: status_available_shards
      help: "The ControllerRing's number of available shards observed by the ControllerRing controller"
      each:
        type: Gauge
        gauge:
          path: [status, availableShards]
