apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    group: apps
    kind: Deployment
    name: webhosting-operator
    namespace: webhosting-system
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --zap-devel
