apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  app.kubernetes.io/name: controller-sharding
  app.kubernetes.io/component: shard

images:
- name: shard
  newName: ghcr.io/timebertt/kubernetes-controller-sharding/shard
  newTag: latest

resources:
- ../controllerring
- deployment.yaml
- rbac.yaml
- serviceaccount.yaml
