name: images

on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:

jobs:
  images:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-releases depName=ko-build/ko
      KO_VERSION: v0.18.0
    steps:
    - uses: actions/checkout@v4
      with:
        # fetch all history so that git describe works (needed by hack/prepare-image-metadata.sh)
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - uses: ko-build/setup-ko@v0.9
      with:
        version: ${{ env.KO_VERSION }}
    - name: Prepare image metadata
      id: meta
      run: ./hack/prepare-image-metadata.sh
    - name: ko build
      run: |
        set -ex

        # prepare .ko.yaml to inject build settings into all images
        entrypoints=(
          ./cmd/sharder
          ./cmd/checksum-controller
          ./webhosting-operator/cmd/experiment
          ./webhosting-operator/cmd/webhosting-operator
        )
        
        echo builds: > .ko.yaml
        for entrypoint in "${entrypoints[@]}" ; do
        cat >> .ko.yaml <<EOF
        - main: $entrypoint
          ldflags:
          - |
            {{.Env.LDFLAGS}}
        EOF
        done

        ko build --push=${{ github.event_name != 'pull_request' }} --sbom none --base-import-paths \
          --tags "${{ steps.meta.outputs.tags }}" --image-label "${{ steps.meta.outputs.labels }}" \
          --platform linux/amd64,linux/arm64 \
          "${entrypoints[@]}"
